// Autogenerated Scheme to C++ Code
// File: test.cpp
#include <iostream>
#include "Object.h"
using namespace std;

int main(	cout << 	12 + 5;
	cout << endl;
;
	cout << 	"abc" + "xyz";
	cout << endl;
;
	cout << 	"abc" + 5;
	cout << endl;
}
	return 0;
}